# Site
title:              С нуля до работы
bio:                'Блог о продвижении новичка к профессии программиста'
description:        "<h1>C нуля до работы</h1><h3>Блог о продвижении новичка к профессии программиста.</h3>"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/me.jpg'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             ru_RU
url:                https://joisadler.dev
baseurl:            ""

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   joisadler-github-io

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics:        UA-99322644-1
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              joisadler@gmail.com
twitter:            joisadler
facebook:           joisadler
github-url:         joisadler
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           joisadler
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#medium:            '@joisadler'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist


jekyll-mentions:
    base_url: ""

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
